### ISSUE TITLE
nice job

### ISSUE THREAD

**Issue by hussamsaheb** [VladimirKalachikhin/GooglePhotosURLs#1]
can you make it like this ? 
https://ctrlq.org/google/photos/
it's very helpfull if you do it 
thanks for your work

**Comment by VladimirKalachikhin** [comment]
Test it.

**Comment by hussamsaheb** [comment]
great job Thanks

**Comment by VladimirKalachikhin** [comment]
Inform me when problems.

**Comment by deshitunes** [comment]
> can you make it like this ?
> https://ctrlq.org/google/photos/
> it's very helpfull if you do it
> thanks for your work

Hi, I found this https://zerophotos.herokuapp.com like cool tools also.
